# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83d7906a9748ae07b4e21c8a7ff17e94a9e636e2ad49ddaa41a89c40b73f063c2ddbe6cd4d1b3071dd00a7676ba34619a375a98ee1f4e2c4032ef9ceb26315d6

test:
  secret_key_base: c53a4c62461dc4c5e0f083eaf89852d6be1ad552327f1628b4311bd59ec4a2b7d21ec84991df0dd9a8c969635981599bd990dd4f6b30b37a834c1e4249140b06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
